server:
  port: 8080
eureka:
  client:
    fetchRegistry: true
    registerWithEureka: false
    serviceUrl:
      defaultZone: http://localhost:8085/eureka/

spring:
  application:
    name: proxy
  cloud:
    config:
      uri: http://localhost:8081
      label: configuration

zuul:
  ignoredServices: proxy
  routes:
      service: /service/**
